Refs: #8621 add warning listener
eProsima/Fast-RTPS-docs pull request #190
Opened 2020-09-02 11:03 UTC by jparisu

Signed-off-by: jparisu <javierparis@eprosima.com>

2020-09-02 11:25 UTC, richiware commented
Build status: [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Docs%20Manual&build=609)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Docs%20Manual/609/)

2020-09-02 12:53 UTC, rsanchez15 requested changes

2020-09-02 12:53 UTC, rsanchez15 commented on docs/fastdds/dds_layer/core/entity/entity.rst
> +   keep listener functions simple, and leave the process of such information to the proper class.
```suggestion
   keep listener functions simple, leaving the process of such information to the proper class.
```

2020-09-02 12:53 UTC, rsanchez15 commented on docs/fastdds/dds_layer/core/entity/entity.rst
> +.. note::
I think this is a warning more than a note.

2020-09-02 12:53 UTC, rsanchez15 commented on docs/fastdds/dds_layer/core/entity/entity.rst
> +   Do not to create or delete any Entity from a Listener, since it could lead to an undefined
```suggestion
   Do not to create or delete any Entity within the scope of a Listener member function, since it could lead to an undefined
```

2020-09-02 12:53 UTC, rsanchez15 commented on docs/fastdds/dds_layer/core/entity/entity.rst
> +   behavior. It is recommended instead to use the Listener class as an information channel, and use the upper
```suggestion
   behavior. It is recommended instead to use the Listener class as an information channel and the upper
```

2020-09-03 05:56 UTC, richiware commented
Build status: [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Docs%20Manual&build=610)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Docs%20Manual/610/)

2020-09-03 06:42 UTC, richiware commented
Build status: [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Docs%20Manual&build=611)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Docs%20Manual/611/)

2020-09-03 07:31 UTC, rsanchez15 approved these changes
LGTM

2020-09-03 07:32 UTC, merged