Added skip xml environment value documentation [9409]
eProsima/Fast-RTPS-docs pull request #195
Opened 2020-09-25 08:50 UTC by imontesino

Adds documentation for added feature in eprosima/Fast-DDS#1350.
Signed-off-by: imontesino <monte.igna@gmail.com>

2020-09-25 09:07 UTC, richiware commented
Build status: [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Docs%20Manual&build=617)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Docs%20Manual/617/)

2020-09-28 05:17 UTC, MiguelCompany requested changes
Just to keep linters happy

2020-09-28 05:17 UTC, MiguelCompany commented on docs/fastdds/env_vars/env_vars.rst
> +    +------------------------------------------------------------------+
```suggestion
    +------------------------------------------------------------------+

```

2020-09-28 06:04 UTC, richiware commented
Build status: [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Docs%20Manual&build=618)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Docs%20Manual/618/)

2020-09-28 06:55 UTC, MiguelCompany approved these changes

2020-09-28 06:57 UTC, merged