RTPS payload pool
eProsima/Fast-RTPS-docs pull request #199
Opened 2020-10-07 14:47 UTC by IkerLuengo

Documenting the new PayloadPool on the RTPS layer:

- Add the IPayloadPool interface to the API-ref
- Add the IChangePool interface to the API-ref
- Describe the functionality of the pool
- Describe how the default implementation works
- Explain how to create endpoints with a custom pool
- Provide an example using a custom pool

**note**: Keeping it as draft until all implementations are in place in Fast DDS, as the test of this pull request would fail otherwise.

2020-10-07 15:10 UTC, richiware commented
Build status: [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Docs%20Manual&build=627)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Docs%20Manual/627/)

2020-10-09 07:54 UTC, MiguelCompany requested changes

2020-10-09 07:54 UTC, MiguelCompany commented on code/CodeTester.cpp
> +            CacheChange_t& cache_change) override
```suggestion
                uint32_t size,
                CacheChange_t& cache_change) override
```

2020-10-09 07:54 UTC, MiguelCompany commented on code/CodeTester.cpp
> +            // Tell the CacheChange who needs to release ist payload
```suggestion
            // Tell the CacheChange who needs to release its payload
```

2020-10-09 07:54 UTC, MiguelCompany commented on code/CodeTester.cpp
> +            // Dealloc the buffer of the payload
```suggestion
        {
            // Ensure precondition
            assert (this == cache_change.payload_owner());

            // Dealloc the buffer of the payload
```

2020-10-09 07:54 UTC, MiguelCompany commented on code/CodeTester.cpp
> +            // Tell the CacheChange who needs to release ist payload
```suggestion
            // Tell the CacheChange who needs to release its payload
```

2020-10-09 07:54 UTC, MiguelCompany commented on code/CodeTester.cpp
> +    // Write and Read operations work as usual, but take the Payloads from the poo.
```suggestion
    // Write and Read operations work as usual, but take the Payloads from the pool.
```

2020-10-09 07:54 UTC, MiguelCompany commented on docs/fastdds/rtps_layer/rtps_layer.rst
> +
May be interesting to add a note regarding the requirements for using a custom pool in the context of standard RTPS serialization. Mentioning section 10.2 of the RTPS standard and the 4 bytes required for `representation_identifier` and `representation_options`.

2020-10-09 07:54 UTC, MiguelCompany commented on docs/fastdds/rtps_layer/rtps_layer.rst
> +Payloads are preallocated for the initially allocated :class:`CacheChange_t`.
This also applies to PREALLOCATED_MEMORY_MODE

2020-10-13 07:47 UTC, IkerLuengo commented on code/CodeTester.cpp
> +    // Write and Read operations work as usual, but take the Payloads from the poo.
:+1: 
that would be a shitty Payload

2020-10-13 09:29 UTC, richiware commented
Build status: [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Docs%20Manual&build=628)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Docs%20Manual/628/)

2020-10-13 10:10 UTC, richiware commented
Build status: [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Docs%20Manual&build=629)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Docs%20Manual/629/)

2020-10-13 11:59 UTC, richiware commented
Build status: [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Docs%20Manual&build=630)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Docs%20Manual/630/)

2020-10-13 15:40 UTC, richiware commented
Build status: [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Docs%20Manual&build=632)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Docs%20Manual/632/)

2020-10-14 06:25 UTC, MiguelCompany approved these changes

2020-10-14 06:26 UTC, merged