RTPS payload pool
eProsima/Fast-RTPS-docs pull request #202
Opened 2020-10-30 06:55 UTC by MiguelCompany

* Refs 9544. Adding new interfaces to API-ref

Signed-off-by: Iker Luengo <ikerluengo@eprosima.com>

* Refs 9544. alias for references to API-ref

Signed-off-by: Iker Luengo <ikerluengo@eprosima.com>

* Refs 9544. Update RTPS doc with references to API-ref

Signed-off-by: Iker Luengo <ikerluengo@eprosima.com>

* Refs 9544. Documentation of Payload pool

Signed-off-by: Iker Luengo <ikerluengo@eprosima.com>

* Refs 9544. Example with custom Payload pool

Signed-off-by: Iker Luengo <ikerluengo@eprosima.com>

* Refs 9544. Suggestions and documentation check errors

Signed-off-by: Iker Luengo <ikerluengo@eprosima.com>

2020-10-30 07:13 UTC, richiware commented
Build status: [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Docs%20Manual&build=643)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Docs%20Manual/643/)

2020-11-03 15:46 UTC, richiware commented
Build status: [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Docs%20Manual&build=648)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Docs%20Manual/648/)

2020-11-05 08:54 UTC, richiware commented
Build status: [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Docs%20Manual&build=649)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Docs%20Manual/649/)

2020-11-13 10:20 UTC, EduPonz requested changes

2020-11-13 10:20 UTC, EduPonz commented on docs/fastdds/api_reference/rtps/history/history.rst
> +    /fastdds/api_reference/rtps/history/IPayloadPool
Alphabetical order

2020-11-13 10:20 UTC, EduPonz commented on docs/03-exports/aliases-api.include
> +
```suggestion
```

2020-11-13 10:20 UTC, EduPonz commented on code/CodeTester.cpp
> +    //Request a change from the writer
```suggestion
    // Request a change from the writer
```

2020-11-13 10:20 UTC, EduPonz commented on code/CodeTester.cpp
> +    //Insert change into the history. The Writer takes care of the rest.
```suggestion
    // Insert change into the history. The Writer takes care of the rest.
```

2020-11-13 10:20 UTC, EduPonz commented on code/CodeTester.cpp
> +            // ensure precondition
```suggestion
            // Ensure precondition
```

2020-11-13 10:20 UTC, EduPonz commented on code/CodeTester.cpp
> +            assert (this == cache_change.payload_owner());
Precondition only check in debug, I guess that's alright for the example
```suggestion
            assert(this == cache_change.payload_owner());
```

2020-11-13 10:20 UTC, EduPonz commented on code/CodeTester.cpp
> +
```suggestion
```

2020-11-16 16:27 UTC, richiware commented
Build status: [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Docs%20Manual&build=662)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Docs%20Manual/662/)

2020-11-16 16:27 UTC, MiguelCompany commented on docs/fastdds/rtps_layer/rtps_layer.rst
> +They are located in `examples/RTPSTest_as_socket` and in `examples/RTPSTest_registered`
Links have been added

2020-11-16 17:00 UTC, richiware commented
Build status: [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Docs%20Manual&build=664)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Docs%20Manual/664/)

2020-11-17 07:06 UTC, EduPonz approved these changes
LGTM :medal_sports:

2020-11-17 07:06 UTC, merged