Gradle installation note [9827]
eProsima/Fast-RTPS-docs pull request #206
Opened 2020-11-05 11:49 UTC by imontesino

Signed-off-by: Ignacio Montesino <ignaciomontesino@eprosima.com>

2020-11-05 12:07 UTC, JLBuenoLopez-eProsima requested changes
Have you checked if the script works correctly in MacOS platform?

2020-11-05 12:07 UTC, JLBuenoLopez-eProsima commented on docs/installation/sources/sources_linux.rst
> +        ./gradlew assebmle
```suggestion
        ./gradlew assemble
```

2020-11-05 12:07 UTC, JLBuenoLopez-eProsima commented on docs/installation/sources/sources_linux.rst
> +    If errors occur during compilation or you do not wish to install gradle, executable script is included which will
```suggestion
    If errors occur during compilation or you do not wish to install gradle, an executable script is included which will
```

2020-11-05 12:07 UTC, JLBuenoLopez-eProsima commented on docs/installation/sources/sources_linux.rst
> +    download a temporary gradle for the compilation step.
```suggestion
    download gradle temporarily for the compilation step.
```

2020-11-05 12:07 UTC, JLBuenoLopez-eProsima commented on docs/installation/sources/sources_mac.rst
> +    If errors occur during compilation or you do not wish to install gradle, executable script is included which will
```suggestion
    If errors occur during compilation or you do not wish to install gradle, an executable script is included which will
```

2020-11-05 12:07 UTC, JLBuenoLopez-eProsima commented on docs/installation/sources/sources_mac.rst
> +    download a temporary gradle for the compilation step.
```suggestion
    download gradle temporarily for the compilation step.
```

2020-11-05 12:07 UTC, JLBuenoLopez-eProsima commented on docs/installation/sources/sources_mac.rst
> +        ./gradlew assebmle
```suggestion
        ./gradlew assemble
```

2020-11-10 08:18 UTC, imontesino commented
Waiting on eProsima/Fast-DDS-Gen/pull/46 for correct behavior on macOS.

2020-11-10 08:49 UTC, richiware commented
Build status: [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Docs%20Manual&build=651)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Docs%20Manual/651/)

2020-11-10 09:11 UTC, JLBuenoLopez-eProsima submitted a review, later dismissed
LGTM with green CI

2020-11-10 09:37 UTC, richiware commented
Build status: [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Docs%20Manual&build=652)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Docs%20Manual/652/)

2020-11-11 12:04 UTC, richiware commented
Build status: [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Docs%20Manual&build=653)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Docs%20Manual/653/)

2020-11-11 12:15 UTC, EduPonz approved these changes
LGTM

2020-11-11 14:25 UTC, merged