Gradle installation note <2.0.x> [9882]
eProsima/Fast-RTPS-docs pull request #208
Opened 2020-11-12 07:25 UTC by imontesino

Signed-off-by: Ignacio Montesino <ignaciomontesino@eprosima.com>

2020-11-12 07:40 UTC, richiware commented
Build status: [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Docs%20Manual&build=655)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Docs%20Manual/655/)

2020-11-20 12:10 UTC, EduPonz requested changes

2020-11-20 12:10 UTC, EduPonz commented on docs/installation/sources/sources_linux.rst
> +    download a gradle temporarily for the compilation step.
Same for MAC
```suggestion
    If errors occur during compilation, or *Gradle* installation is wished to be avoided, an executable script is included which will
    download a temporal *Gradle* for the compilation step.
```

2020-11-20 12:16 UTC, EduPonz commented
This PR requieres rebasing

2020-11-20 12:24 UTC, richiware commented
Build status: [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Docs%20Manual&build=672)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Docs%20Manual/672/)

2020-11-24 10:36 UTC, richiware commented
Build status: [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Docs%20Manual&build=673)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Docs%20Manual/673/)

2020-11-24 10:44 UTC, JLBuenoLopez-eProsima approved these changes
LGTM

2020-11-24 14:14 UTC, EduPonz approved these changes
LGTM

2020-11-24 14:14 UTC, merged