v2.1.0 release notes
eProsima/Fast-RTPS-docs pull request #210
Opened 2020-11-16 16:21 UTC by EduPonz

Signed-off-by: EduPonz <eduardoponz@eprosima.com>

2020-11-16 16:33 UTC, MiguelCompany submitted a review, later dismissed

2020-11-16 16:56 UTC, richiware commented
Build status: [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Docs%20Manual&build=663)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Docs%20Manual/663/)

2020-11-17 06:19 UTC, rsanchez15 requested changes

2020-11-17 06:19 UTC, rsanchez15 commented on docs/notes/notes.rst
> +* Fixed assertion failure on persistent writers
There is a *note* at the end of the [2.0.1 release notes](https://github.com/eProsima/Fast-RTPS-docs/blob/master/docs/notes/previous_versions/v2.0.1.rst) that I would move to the end of these release notes.

2020-11-17 06:27 UTC, rsanchez15 approved these changes

2020-11-17 06:42 UTC, richiware commented
Build status: [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Docs%20Manual&build=665)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Docs%20Manual/665/)

2020-11-17 06:51 UTC, merged