[21325] Remove all code related to FAST CDR v1
eProsima/Fast-RTPS-docs pull request #882
Opened 2024-07-18 12:56 UTC by EduPonz

## Description

Fast DDS Docs counterpart of:

* eprosima/fast-dds#5073

## Contributor Checklist

- [x] Commit messages follow the project guidelines. 
- _N/A_: Code snippets related to the added documentation have been provided.
- [x] Documentation tests pass locally.
- _N/A_ Applicable backports have been included in the description.

## Reviewer Checklist

- [x] The PR has a milestone assigned.
- [x] The title and description correctly express the PR's purpose.
- [x] Check contributor checklist is correct.
- [x] CI passes without warnings or errors.

2024-07-22 05:26 UTC, richiware requested changes

2024-07-22 05:26 UTC, richiware commented on docs/conf.py
> +        _fastdds_python \
```suggestion
        -interface  _fastdds_python \
```

2024-07-24 07:06 UTC, richiware approved these changes

2024-07-24 10:33 UTC, EduPonz commented
A green RTD build with the correct branches [here](https://eprosima-fast-rtps--882.org.readthedocs.build/en/882/). Dropping the test commit and running CI

2024-07-24 13:24 UTC, MiguelCompany approved these changes

2024-07-24 13:25 UTC, merged